version: '3.9'
services:
  node:
    build: 
      context: ./connexone-backend
      dockerfile: Dockerfile
    container_name: connexone-employee-backend
    ports:
      - '4000:4000'

  react:
    build: 
      context: ./connexone-frontend
      dockerfile: Dockerfile
    container_name: connexone-employee-frontend
    ports:
      - '3000:3000'
    stdin_open: true
